name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [17]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node environment 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          check-latest: true
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm ci --prefer-offline --no-audit --no-optional

      - name: Run linter 👀
        run: npm run lint

      - name: Run test 🥳
        run: npm run test
